-- MySQL Script generated by MySQL Workbench
-- 04/18/16 10:11:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema VicenteDavila
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `VicenteDavila` ;

-- -----------------------------------------------------
-- Schema VicenteDavila
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `VicenteDavila` DEFAULT CHARACTER SET utf8 ;
USE `VicenteDavila` ;

-- -----------------------------------------------------
-- Table `VicenteDavila`.`phone_numbers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VicenteDavila`.`phone_numbers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `home_phone` VARCHAR(45) NULL,
  `work_phone` VARCHAR(45) NULL,
  `mobile_phone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VicenteDavila`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VicenteDavila`.`person` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `document_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `gender` ENUM('MALE', 'FEMALE') NULL,
  `home_address` VARCHAR(140) NULL,
  `email` VARCHAR(45) NULL,
  `picture` BLOB NULL,
  `phone_numbers_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_person_phone_number1_idx` (`phone_numbers_id` ASC),
  UNIQUE INDEX `document_id_UNIQUE` (`document_id` ASC),
  CONSTRAINT `fk_person_phone_number1`
    FOREIGN KEY (`phone_numbers_id`)
    REFERENCES `VicenteDavila`.`phone_numbers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VicenteDavila`.`parent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VicenteDavila`.`parent` (
  `id` INT UNSIGNED NOT NULL,
  `work_address` VARCHAR(140) NULL,
  `marital_status` ENUM('MARRIED', 'SINGLE', 'DIVORCED', 'WIDOWED') NOT NULL,
  `instruction_grade` VARCHAR(45) NULL,
  `craft_profession` VARCHAR(45) NULL,
  `live_with_the_student` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_parent_person`
    FOREIGN KEY (`id`)
    REFERENCES `VicenteDavila`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VicenteDavila`.`legal_representative`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VicenteDavila`.`legal_representative` (
  `id` INT UNSIGNED NOT NULL,
  `work_address` VARCHAR(140) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_legal_representative_person1_idx` (`id` ASC),
  CONSTRAINT `fk_legal_representative_person1`
    FOREIGN KEY (`id`)
    REFERENCES `VicenteDavila`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VicenteDavila`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VicenteDavila`.`users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `remember_token` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `type` ENUM('admin', 'teacher', 'administrativePersonLevel1', 'administrativePersonLevel2') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VicenteDavila`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VicenteDavila`.`teacher` (
  `id` INT UNSIGNED NOT NULL,
  `teacher_code` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_teacher_person1`
    FOREIGN KEY (`id`)
    REFERENCES `VicenteDavila`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VicenteDavila`.`section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VicenteDavila`.`section` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `grade` ENUM('1°', '2°', '3°', '4°', '5°', '6°') NULL,
  `section_letter` VARCHAR(2) NULL,
  `teacher_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_section_teacher1_idx` (`teacher_id` ASC),
  CONSTRAINT `fk_section_teacher1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `VicenteDavila`.`teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VicenteDavila`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VicenteDavila`.`student` (
  `id` INT UNSIGNED NOT NULL,
  `height` FLOAT NULL,
  `weight` FLOAT NULL,
  `born_place` VARCHAR(45) NULL,
  `born_date` DATE NULL,
  `pedagogical_difficulties` VARCHAR(60) NULL,
  `diseases_affecting` VARCHAR(45) NULL,
  `after_school_activities` VARCHAR(45) NULL,
  `status` INT(1) NULL,
  `teacher_id` INT UNSIGNED NULL,
  `relationship_with_legal_representative` VARCHAR(45) NULL,
  `parent_id` INT UNSIGNED NULL,
  `legal_representative_id` INT UNSIGNED NOT NULL,
  `section_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_student_teacher1_idx` (`teacher_id` ASC),
  INDEX `fk_student_parent1_idx` (`parent_id` ASC),
  INDEX `fk_student_legal_representative1_idx` (`legal_representative_id` ASC),
  INDEX `fk_student_section1_idx` (`section_id` ASC),
  CONSTRAINT `fk_table1_person1`
    FOREIGN KEY (`id`)
    REFERENCES `VicenteDavila`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_teacher1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `VicenteDavila`.`teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_parent1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `VicenteDavila`.`parent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_legal_representative1`
    FOREIGN KEY (`legal_representative_id`)
    REFERENCES `VicenteDavila`.`legal_representative` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_section1`
    FOREIGN KEY (`section_id`)
    REFERENCES `VicenteDavila`.`section` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VicenteDavila`.`brotherhood`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VicenteDavila`.`brotherhood` (
  `student_id` INT UNSIGNED NOT NULL,
  `student_id1` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`student_id`, `student_id1`),
  INDEX `fk_student_has_student_student2_idx` (`student_id1` ASC),
  INDEX `fk_student_has_student_student1_idx` (`student_id` ASC),
  CONSTRAINT `fk_student_has_student_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `VicenteDavila`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_has_student_student2`
    FOREIGN KEY (`student_id1`)
    REFERENCES `VicenteDavila`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VicenteDavila`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VicenteDavila`.`migrations` (
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT(11) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VicenteDavila`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VicenteDavila`.`password_resets` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `VicenteDavila`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `VicenteDavila`;
INSERT INTO `VicenteDavila`.`users` (`id`, `name`, `email`, `password`, `remember_token`, `created_at`, `updated_at`, `type`) VALUES (1, 'Administrador', 'admin@admin.com', '$2y$10$uBNbcDO24s/zP5zeGaOJCe0lzhRtuR2cgxoG6OLkVBw/j9nV982gm', '', '2016-04-13 18:43:00', '2016-04-13 18:43:00', 'admin');

COMMIT;

